### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by AwesomeIsMatt** [berbb/PortAIO-Loader#117]
Whenever kalista uses her ult on me, I crash.

Whenever Yi does Q I crash.  

using aramdet / sfx/ elutility/ ezenvade

**Comment by Lemonadez** [comment]
Cant tell u have too much addon.

SFX Utility - So many settings might crashed you
EzEvade.

In Order to trim down your crashing. Only use Champion Mode.. Otherwise cant exactly get to know the problem cuz SFX Utility is AIO tracker/items/ward/drawings...

Dont use SFX utility. Just use Champion mode and see if that it crash you. If it didnt crash u, then that between ezevade or sfx utlity.
