### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by Wa1L** [berbb/PortAIO-Loader#48]
The Quality of this port is definitely better than V1 , but the problem is i m getting crashes with every  champ even utilities are disabled , that happens when someone flashes / appear out of bushes or even randomly , sometimes at the beggining of the game and i get no errors in console though

**Comment by rajuritik** [comment]
Beta™

**Comment by berbb** [comment]
https://www.elobuddy.net/topic/37872-fps-drop/
https://www.elobuddy.net/topic/37886-eb/
https://www.elobuddy.net/topic/37873-still-crashing/
https://www.elobuddy.net/topic/37380-mid-ingame-crash/
https://www.elobuddy.net/topic/37793-ashe-r-constantly-crashing-game/
https://www.elobuddy.net/topic/37767-crashing/
https://www.elobuddy.net/topic/37735-random-crashes/

As of now, it's hard to fix anything because EloBuddy is unstable at the moment which unfortunately makes PortAIO unstable.

**Comment by berbb** [comment]
EBs issue seems to have been fixed, and I've been working hard to prevent crashes in 1.0.0.4, so wait for 1.0.0.4 and some of these issues should be fixed.
