### ISSUE TITLE
How to add addons in PortAIO--Loader??

### ISSUE THREAD

**Issue by Justifiied** [berbb/PortAIO-Loader#79]
Hi Berb..i have port some assemblies that will can work with EloBuddy and PortAIO.Common and i want to add them to PortAIO-Loader..So how can i do this?
Or i can sent them to you to add them to PortAIO-Loader
I'm admire you for your hard work because it was very difficult to do this and i want to help you as i can..

**Comment by edubuenoz** [comment]
You can`t do this because portaio its not open source so ask for berb port whatever assembly u want but he can`t do now because he trying to fix the crashes.

**Comment by berbb** [comment]
You can't unless you have the source. And if not as difficult as you think, I have a tool that will port anything lol

**Comment by Justifiied** [comment]
Man i know that porting is not so difficult..i have ported more than 20 addons in 1 day without anytool but i will make one ..
I have 2 questions.
1)That bugs are from PortAIO.Common or from your ported scripts?because the addons in official l# works nice without crashes..
2)how you add L# menu on your ported scripts...
I'm Programmer too and i can really help to fix it
(but if the problems are not from porting but from PortAIO.Common,i need your help to understand what you did on it,)
if you want sent me an email here:
Justified4444@gmail.com

**Comment by berbb** [comment]
lmfao, make your own PortAIO then if you're so good at it.

1). The bugs are from the script, EB Core, and PortAIO.Common. Nothing that is ported will EVER be the same as the original.

2). Since you know how to port, do you it yourself. And port your own L# common.

No, I will not assist you in porting, you can do it yourself and learn it yourself like I did.
